### PR TITLE
Fix cursor position

### PR DESCRIPTION
**Pull request by lvim-tech**
First run `zz zv` and then set cursor position

### CODE REVIEW

**Comment by DNLHC** [comment]
That will make preview window centering with `zz` command not work properly, it should be called after setting the new cursor position. Same goes for `zv` command.

**Comment by DNLHC** [comment]
seems like splitting the `zz` and `zv` commands does the trick, like so:
```lua
vim.cmd('norm! zz')
vim.cmd('norm! zv')
```
Could you test it?

**Comment by lvim-tech** [comment]
First zv znd then zz?
```lua
vim.cmd('norm! zv')
vim.cmd('norm! zz')
```

**Comment by DNLHC** [comment]
Don't think order matters, but they should be called after setting the new cursor position

**Comment by lvim-tech** [comment]
Tested, works

**Comment by DNLHC** [comment]
Thanks!

**Comment by lvim-tech** [comment]
Thanks for amazing plugin!

**Pull request merged**
